### ISSUE TITLE
用这个进行本地化之后，“我的设备中by xiaomi.eu的字样会消失”变成了“开发版”，后续升级通道是走国内开发版了还是继续走欧洲版？

### ISSUE THREAD

**Issue by TurnOffNOD** [kooritea/mipay-extract#14]
用这个对欧洲版进行了本地化之后，现在“我的设备”当中的“by xiaomi.eu的字样”消失了，但是它却显示的是“开发版”了，系统升级显示的也是“目前已安装MIUI12.6|21.2.31|（weekly）”，“开发版”和（weekly）字样这是欧洲版的标识还是国内周更版的？之后升级是在哪个通道升级的？
谢谢解答。

**Comment by kooritea** [comment]
欧版本质是开发版，现在只是把设置本地化了所以显示成开发版，之后更新依然是走欧版的更新。
建议直接去eu下载然后进rec手动刷，不要用系统自带的更新。

**Comment by TurnOffNOD** [comment]
> 
> 
> 欧版本质是开发版，现在只是把设置本地化了所以显示成开发版，之后更新依然是走欧版的更新。
> 建议直接去eu下载然后进rec手动刷，不要用系统自带的更新。

感谢解答。升级了两次知道继续走欧洲版升级通道了。就是看“有没有更新”这件事方便一点，升级还是会自己手动刷的。

**Comment by TurnOffNOD** [comment]
> 
> 
> 欧版本质是开发版，现在只是把设置本地化了所以显示成开发版，之后更新依然是走欧版的更新。
> 建议直接去eu下载然后进rec手动刷，不要用系统自带的更新。

它自己的升级就是走欧洲版，而且自己的升级下载的安装包就是全量安装包。直接下载之后重启进rec手动刷就行了。
