### ISSUE TITLE
小米钱包、日历、短信等多个APP打不开

### ISSUE THREAD

**Issue by IntangibleW** [kooritea/mipay-extract#21]
机型Mix 3, 系统MIUI12.5.1 EU，使用方法二。
刷入模块后桌面有小米钱包图标，但名称显示的是包名，且打开会闪退
另外按照指示删除/data/system/package_cache/下的文件夹后，日历桌面名称显示为false，且打开闪退。
负一屏、短信这些都不能正常使用。也没有发现黄叶、通知聚合等功能。想问一下怎么还原。

**Comment by kooritea** [comment]
在magisk删除模块就还原了，建议用这个 https://blog.minamigo.moe/archives/184

**Comment by IntangibleW** [comment]
> 在magisk删除模块就还原了，建议用这个 https://blog.minamigo.moe/archives/184

刷过的，刷完日历天气短信照样打不开😂

**Comment by IntangibleW** [comment]
另外刷过这个模块后，在最近任务中划掉APP后直接杀进程了。这也是本地化的一个特性吗？

**Comment by kooritea** [comment]
是的，国内版的任务管理器是直接杀整个应用，eu版只会关闭应用的活动但是会保留应用的服务

**Comment by IntangibleW** [comment]
貌似shamiko的白名单模式会引发上述问题，我这里把白名单关了就正常了。
