### ISSUE TITLE
mi10方法二刷入后权限管理打不开，导致无法授权，其他应用也打不开，方法一刷入后在第三方应用上长按没有粘贴选项

### ISSUE THREAD

**Issue by Lambda1107** [kooritea/mipay-extract#6]
刷了大佬提供的包之后无法粘贴，于是自己编译了一个，粘贴是可以了，权限管理又打不开了
自提取包是eufix-20.12.10-UMI-magisk.zip
magisk版本是21100
求大佬看看

**Comment by kooritea** [comment]
先尝试删除/data/system/package_cache/下的文件夹

20.12.10我还没尝试过，可能更新过
我现在还在20.11.5… 或者你可以尝试更早之前的包来提取，这并不影响，刷完记得删除/data/system/package_cache/下的文件夹

**Comment by Lambda1107** [comment]
> 先尝试删除/data/system/package_cache/下的文件夹
> 
> 20.12.10我还没尝试过，可能更新过
> 我现在还在20.11.5… 或者你可以尝试更早之前的包来提取，这并不影响，刷完记得删除/data/system/package_cache/下的文件夹

谢谢大佬回复，删除/data/system/package_cache/下的文件夹我试过了，还是不行，我等会试试换个版本

**Comment by Lambda1107** [comment]
用国内V12.0.11.0版系统提取之后，日历没有阴历，短信没变，但是没有其他bug

**Comment by kooritea** [comment]
不用开发版提吗…

日历那个因为混淆了要改的点每几个版本就变一次，版本差太远我没有兼容过的就不行了

**Comment by Lambda1107** [comment]
20.10.30别的问题都没有了，有小米钱包，但是钱包里没有公交卡选项……

**Comment by Lambda1107** [comment]
![IMG_20201215_121328](https://user-images.githubusercontent.com/71176391/102170444-56c78200-3ecf-11eb-920b-b7b34ddd64a5.jpg)

**Comment by kooritea** [comment]
桌面信息助手里应该也有公交卡，在那里进入会怎么样？

**Comment by Lambda1107** [comment]
> 桌面信息助手里应该也有公交卡，在那里进入会怎么样？

那里没有公交卡……

**Comment by kooritea** [comment]
该不会是刷错机型或者你改过build.prop的机型吧…
看起来是判断你的手机没有nfc了

**Comment by Lambda1107** [comment]
> 该不会是刷错机型或者你改过build.prop的机型吧…
> 看起来是判断你的手机没有nfc了

应该没刷错，也没改过build.prop，可能还是版本的问题，我rom是安卓10的，但是模块从安卓11的包里提取出来的，不知道有没有影响，我现在在试

**Comment by kooritea** [comment]
那试试最后一个安卓10的包？

**Comment by Lambda1107** [comment]
> 那试试最后一个安卓10的包？

我也是这么想的，现在在下载

**Comment by Lambda1107** [comment]
解决了，从最后一个安卓10的包里提取的，暂时没发现问题。
magisk版本20.4
果然不同的安卓版本之间差别还挺大的。
建议大佬可以写在注意事项里
感谢大佬指点！

**Comment by Lambda1107** [comment]
日历还是不适配😂

**Comment by kooritea** [comment]
把日历apk发上来我看看
/data/app/Calendar/Calendar.apk

**Comment by Lambda1107** [comment]
[Uploading Calendar.zip…]()

**Comment by kooritea** [comment]
把cleaner-fix.sh 213行的0x7f04改成0x7f05

**Comment by Lambda1107** [comment]
> 把cleaner-fix.sh 213行的0x7f04改成0x7f05

可以了，大佬牛逼
