### ISSUE TITLE
小米10尊享版 稳定版刷机：1. 日历报错；2. 默认浏览器的下载失灵

### ISSUE THREAD

**Issue by cnryon** [kooritea/mipay-extract#8]
Fork了一个我自己手机的版本：https://github.com/cnryon/mipay-extract-Mi10Ultra

使用的ROM：miui_CAS_V12.0.14.0.QJJCNXM_9437ab21cb_10.0

提取制作magisk包遇到的问题：
1. 日历在执行cleaner-fix.sh报错，错误提示为：Error occurred while disassembling class Lkotlin...和File name too long in java...
2. Magisk刷入后，默认浏览器（com.android.browser)，点击网页上的下载后，有弹窗提示下载，但点击弹窗内的下载没有反应

已经尝试的解决方法：
1. 注释掉cleaner-fix.sh中日历的部分，不对官方rom中的日历进行操作。制作magisk包时使用[发布版](https://github.com/kooritea/mipay-extract/releases/download/v20.11.5/eufix-20.11.5-RAPHAEL-magisk.zip)（v20.11.5/eufix-20.11.5-RAPHAEL-magisk.zip）中的calendar打包，刷入后暂时没有发现使用问题。
2. 默认浏览器没有找到解决办法，使用了其他浏览器（火狐）作为替代，其他浏览器没有出现无法下载问题。

想得到的解决方案：
能够从官方ROM里提取出日历和浏览器两个APP

miui_CAS_V12.0.14.0.QJJCNXM_9437ab21cb_10.0中的Calendar
[Calendar.zip](https://github.com/kooritea/mipay-extract/files/5719384/Calendar.zip)

PS：
对安卓开发不了解，能否解释或提示一下calendar报错的原因吗？我看到另外一个已解决的issue中提到[“把cleaner-fix.sh 213行的0x7f04改成0x7f05”](https://github.com/kooritea/mipay-extract/issues/6#issuecomment-745116612)，原理是什么？我想下次版本更新的时候，如果遇到问题，能够尝试自己解决一下，多谢！

**Comment by kooritea** [comment]
日历那个抛错是反编译的问题和你发的另一个issue里提的没有关系，你把rom包发我看看才行。

浏览器下载没反应的问题这里没有复现
- 试试关掉下载那里的迅雷引擎
- 在cleaner-fix的32行private_apps加一个`priv-app/Browser`就能提取打包进去了

0x7f04那个可以看这里https://github.com/linusyang92/mipay-extract/issues/54
其实就是不同版本的日历判断是否需要显示农历的类和方法被混淆成了不同的名称，要是失效了就要反编译手动查看

**Comment by cnryon** [comment]
感谢！

ROM包下载地址：https://bigota.d.miui.com/V12.0.14.0.QJJCNXM/miui_CAS_V12.0.14.0.QJJCNXM_9437ab21cb_10.0.zip

迅雷引擎关闭试过了，问题依然存在。
